trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore $(solution)
  displayName: 'Restore dependencies'

- script: dotnet build $(solution) --configuration $(buildConfiguration) --no-restore
  displayName: 'Build the project'

- script: dotnet test --configuration $(buildConfiguration) --verbosity normal
  displayName: 'Run tests'
